package meta

const (
	GeneratedBuildTag = "ignore_meta_generated"
	GeneratedComment  = "// Code generated by meta. DO NOT EDIT."
)

const (
	DefaultOutputFilePrefix = "zz_"
	DefaultOutputFileSuffix = "_gen"
)
