// Code generated by meta. DO NOT EDIT.

package testdata

import (
	"context"
	"time"
)

type UserDaoImpl struct {
}

func (_d *UserDaoImpl) DeleteById(ctx context.Context, id int64) int64 {
	panic("implement me")
}

func (_d *UserDaoImpl) FindByBirthdayGte(ctx context.Context, time time.Time) []*User {
	panic("implement me")
}

func (_d *UserDaoImpl) FindById(ctx context.Context, id int64) *User {
	panic("implement me")
}

func (_d *UserDaoImpl) FindByName(ctx context.Context, name string) *User {
	panic("implement me")
}

func (_d *UserDaoImpl) Insert(ctx context.Context, user *User) *User {
	panic("implement me")
}

func (_d *UserDaoImpl) UpdateById(ctx context.Context, id int64, user *User) int64 {
	panic("implement me")
}

type NoneMethodStructAOPIface interface {
}

type SomeStructAOPIface interface {
	PublicMethod(ctx context.Context, id int64) (string, error)
}
